#include "global_manager.h"

const unsigned int list_sprite_tile_offset[] =
{
	SPRITE_TILES_OFFSET + 0 * SPRITE_TILES_NUMBER,
	SPRITE_TILES_OFFSET + 1 * SPRITE_TILES_NUMBER,
	SPRITE_TILES_OFFSET + 2 * SPRITE_TILES_NUMBER,
	SPRITE_TILES_OFFSET + 3 * SPRITE_TILES_NUMBER,
	SPRITE_TILES_OFFSET + 4 * SPRITE_TILES_NUMBER,
};